# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  name: default
  demands:
    - Agent.OS -equals Linux

steps:
  - script: |
  python3.9 --version
displayName: 'Verify Python Version'

- script: |
    python3.9 -m pip install --upgrade pip
    pip3.9 install -r app/requirements.txt
  displayName: 'Install dependencies'

- task: Docker@2
  inputs:
    containerRegistry: 'docker hub connection/3122022'
    repository: '3122022/azure-sample-app1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- script: |
    mkdir -p ~/.kube
    echo "$(KUBECONFIG_CONTENT)" | base64 --decode > ~/.kube/config
  displayName: 'Set up kubeconfig'
  env:
    KUBECONFIG_CONTENT: $(KUBECONFIG_CONTENT)

- script: kubectl apply -f k8s/deployment.yaml
  displayName: 'Deploy to Kubernetes'
  env:
    KUBECONFIG_CONTENT: $(KUBECONFIG_CONTENT)




  #   - script: |
  #   python3.9 --version
  # displayName: 'Verify Python Version'


# trigger:
# - main

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.9'
#     addToPath: true

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'docker hub connection/3122022'
#     repository: '3122022/azure-sample-app'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     tags: 'latest'

# - task: Kubernetes@1
#   inputs:
#     connectionType: 'KubernetesServiceConnection'
#     kubernetesServiceEndpoint: 'k3s-rancher-ubuntu-preview'
#     namespace: 'default'
#     command: 'apply'
#     arguments: '-f k8s/deployment.yaml'
