apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app4
        image: 3122022/azure-sample-app5:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: my-registry-secret     #docker hub secret
